---
- hosts: localhost
  tasks:
    - name: Add bitnami chart repo for PostgreSQL
      kubernetes.core.helm_repository:
        name: bitnami
        repo_url: 'https://charts.bitnami.com/bitnami'

    - name: Deploy external PostgreSQL database
      kubernetes.core.helm:
        name: gitea-postgresql
        chart_ref: bitnami/postgresql
        release_namespace: default
        values:
          auth:
            postgresPassword: 'gitea123'
            database: 'gitea'
          primary:
            persistence:
              enabled: true
              size: 8Gi
          metrics:
            enabled: false

    - name: Add gitea chart repo
      kubernetes.core.helm_repository:
        name: gitea-charts
        repo_url: 'https://dl.gitea.com/charts/'

    - name: Wait for PostgreSQL to be ready
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Pod
        namespace: default
        label_selectors:
          - app.kubernetes.io/name=postgresql
          - app.kubernetes.io/instance=gitea-postgresql
        wait: true
        wait_condition:
          type: Ready
          status: 'True'
        wait_timeout: 300

    - name: Deploy production version of gitea with external database
      kubernetes.core.helm:
        name: gitea-prod
        chart_ref: gitea-charts/gitea
        release_namespace: default
        values_files:
          - values.yaml
